### ISSUE TITLE
[todo] 游戏功能相关代办列表

### ISSUE THREAD

**Issue by HatoYuze** [HatoYuze/phigros-bot#2]
- [ ] 新增随机裁剪图片部分的"猜歌"功能
- [ ] 对`/phi gc`的色块游戏难度进行调整

> -  [ ] 考虑无法使用 `#FFFFFF` 或 `#000000` 等颜色作为揭开的颜色
> -  [ ] 考虑在原始基础上随机裁剪图片

- [ ] 增加功能 `random` 获取随机符合要求的歌曲
